name: 创建 Tag And Release

on:
  push:
    branches:
      - main

jobs:
  create-ReleaseAndTag:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 配置Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: 获取版本
        id: get_version
        run: |
          VERSION=$(date +'%Y%m%d')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 创建版本
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
