

name: 推送docker镜像

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: 推送docker镜像到docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: 登录Docker Hub
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 初始化docker仓库
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dsmggm/autojdck

      - name: 构建推送docker镜像
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            dsmggm/autojdck:latest
            dsmggm/autojdck:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

          
