name: auto_actions

on:
  push:
    branches:
      - main  # 修改为你的默认分支名

jobs:
  PushTo_svjdck:
    runs-on: ubuntu-latest

    steps:
      - name: 设置python版本
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
              
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run:  |
            ls
